services:
  - type: web
    name: coffee-shop-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn coffeeshop_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: coffee-shop-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: coffee-shop-db
    databaseName: coffee_shop
    user: coffee_shop_user
    plan: starter