services:
  - type: web
    name: coffeeshop-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn coffeeshop_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: coffeeshop-db
          property: connectionString
      - key: FRONTEND_URL
        sync: false

databases:
  - name: coffeeshop-db
    databaseName: coffeeshop
    user: coffeeshop
